export interface Keys {
  codigo: string;
  comunidad: string;
}

export const comunidadChimaltenango: Keys[] = [
  { codigo: '0401', comunidad: 'BUENA VISTA SUR (MENONITAS)' },
  { codigo: '0401', comunidad: 'SAN MARCOS PACOC' },
  { codigo: '0401', comunidad: 'SANTA ISABEL 1' },
  { codigo: '0401', comunidad: 'MONTE LOS OLIVOS' },
  { codigo: '0401', comunidad: 'SOCOBAL' },
  { codigo: '0401', comunidad: 'LA ALAMEDA A1' },
  { codigo: '0401', comunidad: 'LOS APOSENTOS' },
  { codigo: '0401', comunidad: 'SAN PABLO' },
  { codigo: '0401', comunidad: 'SAN JOSE BETHANIA' },
  { codigo: '0401', comunidad: 'SANTA ANA' },
  { codigo: '0401', comunidad: 'LAS VICTORIAS' },
  { codigo: '0401', comunidad: 'EL ESFUERZO' },
  { codigo: '0401', comunidad: 'COLONIA SANTA TERESITA' },
  { codigo: '0401', comunidad: 'SAN JOSE LAS FLORES' },
  { codigo: '0401', comunidad: 'SANTA OTILIA' },
  { codigo: '0401', comunidad: 'LA PRIMAVERA' },
  { codigo: '0401', comunidad: 'MONTE CRISTO' },
  { codigo: '0401', comunidad: 'CHOJOPIN' },
  { codigo: '0401', comunidad: 'COLONIA SAN RAFAEL' },
  { codigo: '0401', comunidad: 'ILUCIONES' },
  { codigo: '0401', comunidad: 'MAJADAS' },
  { codigo: '0401', comunidad: 'CARLOS RAMOS' },
  { codigo: '0401', comunidad: 'ZONA 1 (SECTOR 1)' },
  { codigo: '0401', comunidad: 'ZONA 2 (SECTOR 1)' },
  { codigo: '0401', comunidad: 'ZONA 3 (SECTOR 1)' },
  { codigo: '0401', comunidad: 'ZONA 4 (JOYA ARRIBA)' },
  { codigo: '0401', comunidad: 'BUENA VISTA NORTE (PILITA)' },
  { codigo: '0401', comunidad: 'BUENA VISTA NORTE (MELOTO)' },
  { codigo: '0401', comunidad: 'BUENA VISTA NORTE (EL CERRITO)' },
  { codigo: '0401', comunidad: 'LA ALAMEDA A2' },
  { codigo: '0401', comunidad: 'LA ALAMEDA B' },
  { codigo: '0401', comunidad: 'SANTA ISABEL 2' },
  { codigo: '0401', comunidad: 'ZONA 1 (SECTOR 2)' },
  { codigo: '0401', comunidad: 'ZONA 2 (SECTOR 2)' },
  { codigo: '0401', comunidad: 'ZONA 3 (SECTOR 2)' },
  { codigo: '0401', comunidad: 'ZONA 3 (SECTOR 3)' },
  { codigo: '0401', comunidad: 'ZONA 3 (SECTOR 4)' },
  { codigo: '0401', comunidad: 'ZONA 4 (JOYA ABAJO)' },
  { codigo: '0401', comunidad: 'HIERBA BUENA' },
  { codigo: '0401', comunidad: 'PUERTO RICO' },
  { codigo: '0401', comunidad: 'EL VERGEL' },
  { codigo: '0401', comunidad: 'EL REFUGIO' },
  { codigo: '0401', comunidad: 'JORDÁN' },
  { codigo: '0401', comunidad: 'BETHANIA' },
  { codigo: '0401', comunidad: 'RESIDENCIALES BETHANIA' },
  { codigo: '0401', comunidad: 'EL VIEJO TEJAR' },
  { codigo: '0401', comunidad: 'JOYITA' },
  { codigo: '0401', comunidad: 'QUINTAS' },
  { codigo: '0401', comunidad: 'DURAZNO' },
  { codigo: '0401', comunidad: 'SAN JACINTO' },
  { codigo: '0401', comunidad: 'EL JORDAN' },
  { codigo: '0401', comunidad: 'SAN ANTONIO LAS MINAS' },
  { codigo: '0401', comunidad: 'TONAJUYU' },
  { codigo: '0401', comunidad: 'CHIMALTENANGO' },
  { codigo: '0406', comunidad: 'CASCO URBANO' },
  { codigo: '0406', comunidad: 'ZONA 1 BARRIO LA ASUNCIÓN,' },
  { codigo: '0406', comunidad: 'ZONA 2 BARRIO POROMÁ' },
  { codigo: '0406', comunidad: 'ZONA 3 BARRIO PATACABAJ' },
  { codigo: '0406', comunidad: 'ZONA 4 BARRIO SAN ANTONIO' },
  { codigo: '0406', comunidad: 'XETZAC' },
  { codigo: '0406', comunidad: 'CHUACHALI' },
  { codigo: '0406', comunidad: 'MOLINO' },
  { codigo: '0406', comunidad: 'ASUNCION MANZANALES' },
  { codigo: '0406', comunidad: 'SANTA TERESA' },
  { codigo: '0406', comunidad: 'PACHAJ' },
  { codigo: '0406', comunidad: 'CRUZ DE SANTIAGO' },
  { codigo: '0406', comunidad: 'CHUATZITE' },
  { codigo: '0406', comunidad: 'EL MIRADOR' },
  { codigo: '0406', comunidad: 'PUEBLO VIEJO' },
  { codigo: '0406', comunidad: 'PAXIXIL' },
  { codigo: '0406', comunidad: 'PANABAJAL' },
  { codigo: '0406', comunidad: 'XETONOX' },
  { codigo: '0406', comunidad: 'PANIMACOC' },
  { codigo: '0406', comunidad: 'TIKAL' },
  { codigo: '0406', comunidad: 'IXIMCHE' },
  { codigo: '0406', comunidad: 'COLONIA 5 DE OCTUBRE' },
  { codigo: '0406', comunidad: 'SAN LORENZO I' },
  { codigo: '0406', comunidad: 'SAN LORENZO II' },
  { codigo: '0406', comunidad: 'GIRALDA MONTAÑITA' },
  { codigo: '0406', comunidad: 'GIRALDA CAMPO' },
  { codigo: '0406', comunidad: 'COLONIA LOS ANGELES' },
  { codigo: '0406', comunidad: 'GIRALDA FINCA' },
  { codigo: '0406', comunidad: 'LA ARGENTINA' },
  { codigo: '0406', comunidad: 'COLONIA MENONITA' },
  { codigo: '0406', comunidad: 'COLONIA SAN FRANCISCO' },
  { codigo: '0406', comunidad: 'RINCON LA ARGENTINA' },
  { codigo: '0406', comunidad: 'POROMA CENTRO' },
  { codigo: '0406', comunidad: 'CALLE NUEVA' },
  { codigo: '0406', comunidad: 'PATACABAJ I' },
  { codigo: '0406', comunidad: 'LA COLONIA' },
  { codigo: '0406', comunidad: 'PATACABAJ II' },
  { codigo: '0406', comunidad: 'LA CHORRERA' },
  { codigo: '0406', comunidad: 'VISTA HERMOSA' },
  { codigo: '0406', comunidad: 'LAS FLORES' },
  { codigo: '0406', comunidad: 'ASUNCION CENTRO' },
  { codigo: '0406', comunidad: 'SAN ANTONIO I' },
  { codigo: '0406', comunidad: 'COLONIA MANZANALES' },
  { codigo: '0406', comunidad: 'SAN ANTONIO II' },
  { codigo: '0406', comunidad: 'CALIAJ' },
  { codigo: '0406', comunidad: 'CAQUIXAJAY' },
  { codigo: '0406', comunidad: 'PACHALI' },
  { codigo: '0406', comunidad: 'PROTRERILLOS' },
  { codigo: '0406', comunidad: 'XEJAVÍ' },
  { codigo: '0406', comunidad: 'EL TABLON' },
  { codigo: '0406', comunidad: 'CHUATZUNUJ' },
  { codigo: '0406', comunidad: 'CHIVARAVAL' },
  { codigo: '0406', comunidad: 'XENIMAJUYÚ' },
  { codigo: '0406', comunidad: 'XIQUINJUYU' },
  { codigo: '0406', comunidad: 'CASERIO PAMANZANA' },
  { codigo: '0406', comunidad: 'ALDEA VISTA BELLA' },
  { codigo: '0406', comunidad: 'SAN JOSÉ CHIRIJUYÚ' },
  { codigo: '0406', comunidad: 'TZANABAJ' },
  { codigo: '0406', comunidad: 'PACORRAL' },
  { codigo: '0406', comunidad: 'CASERIO LA UNION' },
  { codigo: '0406', comunidad: 'AGUA ESCONDIDA' },
  { codigo: '0406', comunidad: 'ZACULEU' },
  { codigo: '0406', comunidad: 'LA LOMA' },
  { codigo: '0406', comunidad: 'CHICHOY' },
  { codigo: '0406', comunidad: 'CHAJALAJYA' },
  { codigo: '0406', comunidad: 'SAN CARLOS' },
  { codigo: '0406', comunidad: 'SAN VICENTE' },
  { codigo: '0406', comunidad: 'PANIMACHAVAC' },
  { codigo: '0406', comunidad: 'CHIRIJUYU' },
  { codigo: '0406', comunidad: 'PATIO BOLAS' },
  { codigo: '0406', comunidad: 'CRUZ QUEMADA' },
  { codigo: '0406', comunidad: 'PAXOROTOT' },
  { codigo: '0406', comunidad: 'TECPAN GUATEMALA' },
  { codigo: '0406', comunidad: 'XECOXOL' },
  { codigo: '0406', comunidad: 'BUENA VISTA NORTE (PILITA)' },
  { codigo: '0406', comunidad: 'PACHICHIAC' },
  { codigo: '0406', comunidad: 'PAMEZUL' },
  { codigo: '0406', comunidad: 'CHIJACINTO' },
  { codigo: '0404', comunidad: 'COMALAPA' },
  { codigo: '0404', comunidad: 'PRIMER CANTÓN' },
  { codigo: '0404', comunidad: 'SEGUNDO CANTÓN' },
  { codigo: '0404', comunidad: 'TERCER CANTÓN' },
  { codigo: '0404', comunidad: 'CUARTO CANTÓN' },
  { codigo: '0404', comunidad: 'QUINTO CANTÓN' },
  { codigo: '0404', comunidad: 'SEXTO CANTÓN' },
  { codigo: '0404', comunidad: 'SÉPTIMO CANTÓN' },
  { codigo: '0404', comunidad: 'OCTAVO CANTÓN' },
  { codigo: '0404', comunidad: 'CHIPOC' },
  { codigo: '0404', comunidad: 'CHICHOCON' },
  { codigo: '0404', comunidad: 'PAXOT' },
  { codigo: '0404', comunidad: 'PANIMABEY' },
  { codigo: '0404', comunidad: 'LAS DELICIAS' },
  { codigo: '0404', comunidad: 'TZANJUYU' },
  { codigo: '0404', comunidad: 'COLONIA SAN JUAN' },
  { codigo: '0404', comunidad: 'LAS VICTORIAS' },
  { codigo: '0404', comunidad: 'MANZANILLO' },
  { codigo: '0404', comunidad: 'PAXAN' },
  { codigo: '0404', comunidad: 'CHIMIYA' },
  { codigo: '0404', comunidad: 'COJOLJUYU' },
  { codigo: '0404', comunidad: 'PACHITUR' },
  { codigo: '0404', comunidad: 'CHIRIJUYU' },
  { codigo: '0404', comunidad: 'LAS TOMAS' },
  { codigo: '0404', comunidad: 'CHUACAÑA' },
  { codigo: '0404', comunidad: 'CHUWI CRUZ' },
  { codigo: '0404', comunidad: 'CHUASIJ' },
  { codigo: '0404', comunidad: 'XETUNEYCHE' },
  { codigo: '0404', comunidad: 'CHUAQUIXALI' },
  { codigo: '0404', comunidad: 'PANABAJAL 1' },
  { codigo: '0404', comunidad: 'PANABAJAL 2' },
  { codigo: '0404', comunidad: 'PANABAJAL 3' },
  { codigo: '0404', comunidad: 'PANABAJAL 4' },
  { codigo: '0404', comunidad: 'PANABAJAL 5' },
  { codigo: '0404', comunidad: 'PANABAJAL 6' },
  { codigo: '0404', comunidad: 'XETONOX' },
  { codigo: '0404', comunidad: 'XENIMAQUIN' },
  { codigo: '0404', comunidad: 'PAYA' },
  { codigo: '0404', comunidad: 'SIMAJHULEU' },
  { codigo: '0404', comunidad: 'QUIZAYA' },
  { codigo: '0404', comunidad: 'AGUA CALIENTE' },
  { codigo: '0404', comunidad: 'PANIMACAC' },
  { codigo: '0404', comunidad: 'PAQUIXIC' },
  { codigo: '0404', comunidad: 'PATZAJ' },
  { codigo: '0404', comunidad: 'PARAXAQUEN' },
  { codigo: '0404', comunidad: 'PAVIT' },
  { codigo: '0404', comunidad: 'CHICHALI' },
  { codigo: '0404', comunidad: 'SAN JUAN PALIMA' },
  { codigo: '0404', comunidad: 'PAMUMUS' },
  { codigo: '0404', comunidad: 'XIQUIN SANAHÍ' },
  { codigo: '0404', comunidad: 'PARAXAJ' },
  { codigo: '0404', comunidad: 'PANICUY' },
  { codigo: '0403', comunidad: 'BARRIO LA JOYA' },
  { codigo: '0403', comunidad: 'BARRIO EL CALVARIO' },
  { codigo: '0403', comunidad: 'BARRIO SAN GASPAR' },
  { codigo: '0403', comunidad: 'BARRIO EL GUITE' },
  { codigo: '0403', comunidad: 'EL PAJON' },
  { codigo: '0403', comunidad: 'LA JOYA DE QUIMAL' },
  { codigo: '0403', comunidad: 'SANTO DOMINGO QUIMAL' },
  { codigo: '0403', comunidad: 'CARRETAS' },
  { codigo: '0403', comunidad: 'PUEBLO DE DIOS' },
  { codigo: '0403', comunidad: 'CHIARMIRA' },
  { codigo: '0403', comunidad: 'LA PEDRERA' },
  { codigo: '0403', comunidad: 'EL SAUCE XEJUYU' },
  { codigo: '0403', comunidad: 'EL NARANJITO' },
  { codigo: '0403', comunidad: 'CANDELARIA' },
  { codigo: '0403', comunidad: 'CASERIO LA UNION' },
  { codigo: '0403', comunidad: 'SARGENTO' },
  { codigo: '0403', comunidad: 'VARIITUC I' },
  { codigo: '0403', comunidad: 'EL CARMEN' },
  { codigo: '0403', comunidad: 'EL MOLINO' },
  { codigo: '0403', comunidad: 'SAN BARTOLOME' },
  { codigo: '0403', comunidad: 'PATZOCON' },
  { codigo: '0403', comunidad: 'CHIGONZALEZ' },
  { codigo: '0403', comunidad: 'EL SAUCE XESUJ' },
  { codigo: '0403', comunidad: 'PALAMA XESUJ' },
  { codigo: '0403', comunidad: 'LOS PINOS XESUJ' },
  { codigo: '0403', comunidad: 'SAN FRANCISCO XESUJ' },
  { codigo: '0403', comunidad: 'CHIPOCOLAJ' },
  { codigo: '0403', comunidad: 'PACHUM' },
  { codigo: '0403', comunidad: 'SACALA' },
  { codigo: '0403', comunidad: 'XENIMAJUYÚ LOMAS' },
  { codigo: '0403', comunidad: 'XENIMAJUYU CHUISAC' },
  { codigo: '0403', comunidad: 'CHUISAC' },
  { codigo: '0403', comunidad: 'LOS JOMETES' },
  { codigo: '0403', comunidad: 'LO DE SILVA' },
  { codigo: '0403', comunidad: 'CHIRRAMOS' },
  { codigo: '0403', comunidad: 'BUENA ESPERANZA' },
  { codigo: '0403', comunidad: 'SANTA ROSA MERCED' },
  { codigo: '0403', comunidad: 'PERICON' },
  { codigo: '0403', comunidad: 'CERRITOS MERCED' },
  { codigo: '0403', comunidad: 'HORNOS' },
  { codigo: '0403', comunidad: 'TEMPISCAL' },
  { codigo: '0403', comunidad: 'CUCHILLA LOS MAGUEYES' },
  { codigo: '0403', comunidad: 'CHOABAJITO' },
  { codigo: '0403', comunidad: 'LIMONAR' },
  { codigo: '0403', comunidad: 'CHOABAJ GRANDE' },
  { codigo: '0403', comunidad: 'PLAN BUENA VISTA' },
  { codigo: '0403', comunidad: 'PATZAJITO' },
  { codigo: '0403', comunidad: 'LA PROVIDENCIA' },
  { codigo: '0403', comunidad: 'LA COLINA' },
  { codigo: '0403', comunidad: 'PUENTE GOMEZ' },
  { codigo: '0403', comunidad: 'ESPERANCITA' },
  { codigo: '0403', comunidad: 'EL RANCHO' },
  { codigo: '0403', comunidad: 'SAN ISIDRO MAGUEYES' },
  { codigo: '0403', comunidad: 'SAN ANTONIO LA MERCED' },
  { codigo: '0403', comunidad: 'EL RINCON LA MERCED' },
  { codigo: '0403', comunidad: 'JOYA DE DON ELIGIO' },
  { codigo: '0403', comunidad: 'CUCHILLA MOLINO' },
  { codigo: '0403', comunidad: 'SAN ISIDRO CARRETAS' },
  { codigo: '0403', comunidad: 'LAS VENTURAS' },
  { codigo: '0403', comunidad: 'SEMETABAJ' },
  { codigo: '0403', comunidad: 'RIO BLANCO' },
  { codigo: '0403', comunidad: 'XETINAMIT' },
  { codigo: '0403', comunidad: 'LOS TUNAYES' },
  { codigo: '0403', comunidad: 'EL TANQUE' },
  { codigo: '0403', comunidad: 'ELQUETZAL, ROSARIO CANAJAL' },
  { codigo: '0403', comunidad: 'SAN JOSE EL RODEO' },
  { codigo: '0403', comunidad: 'LOS VELASQUEZ' },
  { codigo: '0403', comunidad: 'LA CUMBRE' },
  { codigo: '0403', comunidad: 'LA ESCUELA' },
  { codigo: '0403', comunidad: 'EL AGUACATE' },
  { codigo: '0403', comunidad: 'LA COMUNIDAD' },
  { codigo: '0403', comunidad: 'RIO MOTAGUA' },
  { codigo: '0403', comunidad: 'ESTANCITA' },
  { codigo: '0403', comunidad: 'LOS OSORIOS' },
  { codigo: '0403', comunidad: 'POCOPAN' },
  { codigo: '0403', comunidad: 'EL JOCOTE' },
  { codigo: '0403', comunidad: 'EL RETIRO' },
  { codigo: '0403', comunidad: 'JOYA SANTA ANITA' },
  { codigo: '0403', comunidad: 'SAN JERONIMO' },
  { codigo: '0403', comunidad: 'LOS MAGUEYES' },
  { codigo: '0403', comunidad: 'CIMARRON' },
  { codigo: '0403', comunidad: 'PALO BLANCO' },
  { codigo: '0403', comunidad: 'POTRERILLOS' },
  { codigo: '0403', comunidad: 'LOS MAGUEYALES' },
  { codigo: '0403', comunidad: 'LAS ESCOBAS' },
  { codigo: '0403', comunidad: 'LLANO DE LA NEGRA' },
  { codigo: '0403', comunidad: 'MANZANALES' },
  { codigo: '0403', comunidad: 'CORRALITOS' },
  { codigo: '0403', comunidad: 'LA CONCEPCION' },
  { codigo: '0403', comunidad: 'EL TESORO' },
  { codigo: '0403', comunidad: 'EL CAPULIN' },
  { codigo: '0403', comunidad: 'LA PLAZUELA' },
  { codigo: '0403', comunidad: 'EL CHOCOLATE' },
  { codigo: '0403', comunidad: 'SAJCAU' },
  { codigo: '0403', comunidad: 'SAN ANTONIO EL CORNEJO' },
  { codigo: '0403', comunidad: 'SAN JOSE LAS ROSAS' },
  { codigo: '0403', comunidad: 'COJOMACHAJ' },
  { codigo: '0403', comunidad: 'CHONOXTE' },
  { codigo: '0403', comunidad: 'LLANO GRANDE' },
  { codigo: '0403', comunidad: 'ORATORIO' },
  { codigo: '0403', comunidad: 'CUNCURUN' },
  { codigo: '0403', comunidad: 'CHIRRAMIREZ' },
  { codigo: '0403', comunidad: 'FINCA LA LIBERTAD' },
  { codigo: '0403', comunidad: 'TIERRA COLORADA' },
  { codigo: '0403', comunidad: 'TALPETATE' },
  { codigo: '0403', comunidad: 'EL SAPITO' },
  { codigo: '0403', comunidad: 'SAN JOSE CHOATALUN' },
  { codigo: '0403', comunidad: 'SAN FRANCISCO CHOATALUN' },
  { codigo: '0403', comunidad: 'SAN ANTONIO CHOATALUN' },
  { codigo: '0403', comunidad: 'EL ROSARIO CHOATALUN' },
  { codigo: '0403', comunidad: 'COLONIA CHOATALUN' },
  { codigo: '0403', comunidad: 'CHIPILA' },
  { codigo: '0403', comunidad: 'CHIULEU' },
  { codigo: '0403', comunidad: 'PLATANAR' },
  { codigo: '0403', comunidad: 'CHIPASTOR' },
  { codigo: '0403', comunidad: 'BRASILAR' },
  { codigo: '0403', comunidad: 'VEGA DE GODINEZ' },
  { codigo: '0403', comunidad: 'LAS ILUSIONES' },
  { codigo: '0403', comunidad: 'PIXCAYA' },
  { codigo: '0403', comunidad: 'LLANO GRANDE' },
  { codigo: '0403', comunidad: 'CHI DON JUAN' },
  { codigo: '0403', comunidad: 'ESTANCIA DE LA VIRGEN' },
  { codigo: '0403', comunidad: 'CHISUNUC' },
  { codigo: '0403', comunidad: 'COLONIA NUEVA SAN ANTONIO' },
  { codigo: '0403', comunidad: 'CHITUN' },
  { codigo: '0403', comunidad: 'VALLE DE ORO' },
  { codigo: '0403', comunidad: 'PACOXPON' },
  { codigo: '0403', comunidad: 'ESCOBITAS' },
  { codigo: '0403', comunidad: 'PACOJ CHIJOCON' },
  { codigo: '0403', comunidad: 'PANATZAN' },
  { codigo: '0403', comunidad: 'CRUZ NUEVA' },
  { codigo: '0403', comunidad: 'SAN MIGUEL CHOATALUN' },
  { codigo: '0403', comunidad: 'SANTA TERESA CHOATALUN' },
  { codigo: '0403', comunidad: 'TIOXYA' },
  { codigo: '0403', comunidad: 'PACOJ TRES CRUCES' },
  { codigo: '0403', comunidad: 'PACHAY' },
  { codigo: '0403', comunidad: 'PACHAY NORTE' },
  { codigo: '0403', comunidad: 'SAJCAP ALTO' },
  { codigo: '0403', comunidad: 'XESIGUAN' },
  { codigo: '0403', comunidad: 'CAMBALCOL ALTO' },
  { codigo: '0403', comunidad: 'CAMBALCOL BAJO' },
  { codigo: '0403', comunidad: 'PANICUY' },
  { codigo: '0403', comunidad: 'LOS TABLONES' },
  { codigo: '0403', comunidad: 'SAJCAP BAJO' },
  { codigo: '0403', comunidad: 'LAS GUACAMAYAS' },
  { codigo: '0403', comunidad: 'VEGA DE GODINEZ' },
  { codigo: '0402', comunidad: 'SAN JOSÉ POAQUIL' },
  { codigo: '0402', comunidad: 'CHUATACAJ 1' },
  { codigo: '0402', comunidad: 'PACUL' },
  { codigo: '0402', comunidad: 'XEQUECHELAJ (Xequexelaj)' },
  { codigo: '0402', comunidad: 'SARAJMAC' },
  { codigo: '0402', comunidad: 'CHIRAXAJ' },
  { codigo: '0402', comunidad: 'CHUATACAJ 2' },
  { codigo: '0402', comunidad: 'ZONA 1' },
  { codigo: '0402', comunidad: 'ZONA 2 (SECTOR 1)' },
  { codigo: '0402', comunidad: 'ZONA 3' },
  { codigo: '0402', comunidad: 'ZONA 4' },
  { codigo: '0402', comunidad: 'ZONA 5' },
  { codigo: '0402', comunidad: 'SAQUITACAJ' },
  { codigo: '0402', comunidad: 'PACHUITIATZAN' },
  { codigo: '0402', comunidad: 'HACIENDA MARÍA' },
  { codigo: '0402', comunidad: 'CASERIO  CENTRO' },
  { codigo: '0402', comunidad: 'LOS PINOS' },
  { codigo: '0402', comunidad: 'XEJUYU' },
  { codigo: '0402', comunidad: 'PAREXCHEJ' },
  { codigo: '0402', comunidad: 'LA GARRUCHA' },
  { codigo: '0402', comunidad: 'PATOQUER' },
  { codigo: '0402', comunidad: 'HACIENDA VIEJA' },
  { codigo: '0402', comunidad: 'PALEY' },
  { codigo: '0402', comunidad: 'OJER CAIBAL' },
  { codigo: '0402', comunidad: 'CHIMIXAYA' },
  { codigo: '0402', comunidad: 'PANIMASIGUAN' },
  { codigo: '0402', comunidad: 'NUEVA ESPERANZA' },
  { codigo: '0402', comunidad: 'PALAMA (P/S)' },
  { codigo: '0402', comunidad: 'XEPALAMA' },
  { codigo: '0402', comunidad: 'XEBACIN' },
  { codigo: '0402', comunidad: 'PAXCABALCHE' },
  { codigo: '0402', comunidad: 'CHUACRUZ' },
  { codigo: '0402', comunidad: 'PANIMACAC' },
  { codigo: '0402', comunidad: 'PANEYA' },
  { codigo: '0402', comunidad: 'QUISAYA' },
  { codigo: '0402', comunidad: 'CHUIQUISAYA' },
  { codigo: '0402', comunidad: 'PARUXECHE' },
  { codigo: '0407', comunidad: 'LOS PINOS' },
  { codigo: '0407', comunidad: 'NIMAYA' },
  { codigo: '0407', comunidad: 'SALBALPOP' },
  { codigo: '0407', comunidad: 'LA VEGA' },
  { codigo: '0407', comunidad: 'PATZUN' },
  { codigo: '0407', comunidad: 'SAN JOAQUIN LOS NARANJALES' },
  { codigo: '0407', comunidad: 'SAN JOSE PANIMACHE' },
  { codigo: '0407', comunidad: 'SAN RAFAEL' },
  { codigo: '0407', comunidad: 'EL SITIO' },
  { codigo: '0407', comunidad: 'LA TROMPETA' },
  { codigo: '0407', comunidad: 'PACHIMULIN' },
  { codigo: '0407', comunidad: 'LA PILA' },
  { codigo: '0407', comunidad: 'PACHUT' },
  { codigo: '0407', comunidad: 'LAS CAMELIAS' },
  { codigo: '0407', comunidad: 'SAN LORENZO' },
  { codigo: '0407', comunidad: 'COJOBAL' },
  { codigo: '0407', comunidad: 'CHIPIACUL' },
  { codigo: '0407', comunidad: 'PANIBAJ' },
  { codigo: '0407', comunidad: 'PANIMAQUIN' },
  { codigo: '0407', comunidad: 'CHUINIMACHICAJ' },
  { codigo: '0407', comunidad: 'CHUAQUENUM' },
  { codigo: '0407', comunidad: 'SAN JOSÉ XEPATÁN' },
  { codigo: '0407', comunidad: 'CHUCHUCA' },
  { codigo: '0407', comunidad: 'CHUCHUCA B' },
  { codigo: '0407', comunidad: 'XETZITZI' },
  { codigo: '0407', comunidad: 'XEJOLON' },
  { codigo: '0407', comunidad: 'POPABAJ' },
  { codigo: '0407', comunidad: 'XEATZÁN BAJO' },
  { codigo: '0407', comunidad: 'XICHOY ALTO  ( Chichoy Alto Paraiso)' },
  { codigo: '0407', comunidad: 'XEATZÁN ABAJO' },
  { codigo: '0407', comunidad: 'PARAISO CHICHOY' },
  { codigo: '0407', comunidad: 'CHICHOY BAJO' },
  { codigo: '0407', comunidad: 'XEATZAN  ALTO' },
  { codigo: '0407', comunidad: 'CHUIQUEL' },
  { codigo: '0407', comunidad: 'MOCOLICXOT ALTO' },
  { codigo: '0407', comunidad: 'MOCOLICXOT BAJO' },
  { codigo: '0407', comunidad: 'LAS MERCEDES' },
  { codigo: '0407', comunidad: 'PACOC GRANDE' },
  { codigo: '0407', comunidad: 'PACOC CHIQUITO' },
  { codigo: '0407', comunidad: 'SAQUIYA' },
  { codigo: '0407', comunidad: 'COLONIA EL MILAGRO' },
  { codigo: '0407', comunidad: 'COLONIA KRAKEROY' },
  { codigo: '0407', comunidad: 'COLONIA NORUEGA' },
  { codigo: '0407', comunidad: 'NORTE I' },
  { codigo: '0407', comunidad: 'NORTE II' },
  { codigo: '0407', comunidad: 'NORTE III' },
  { codigo: '0407', comunidad: 'ORIENTE I' },
  { codigo: '0407', comunidad: 'ORIENTE II' },
  { codigo: '0407', comunidad: 'SUR I' },
  { codigo: '0407', comunidad: 'SUR II' },
  { codigo: '0407', comunidad: 'PONIENTE I' },
  { codigo: '0407', comunidad: 'PONIENTE II' },
  { codigo: '0413', comunidad: 'SAN ANDRÉS IZTAPA' },
  { codigo: '0413', comunidad: 'UM. CALDERAS' },
  { codigo: '0413', comunidad: 'SAN CRISTOBAL CENTRO' },
  { codigo: '0413', comunidad: 'CANTON SAN CRISTOBAL STAN' },
  { codigo: '0413', comunidad: 'CANTON SAN CRISTOBAL RESIDENCIAL' },
  { codigo: '0413', comunidad: 'CANTON SAN LORENZO CENTRICO' },
  { codigo: '0413', comunidad: 'CANTON SAN LORENZO MIRADOR' },
  { codigo: '0413', comunidad: 'CANTON SAN LORENZO 20 LAVADEROS' },
  { codigo: '0413', comunidad: 'SAN ANTONIO LAS CONCHITAS' },
  { codigo: '0413', comunidad: 'SAN ANTONIO LA TOMA' },
  { codigo: '0413', comunidad: 'SAN PEDRO SAN PABLO LA NAVIDEÑA' },
  { codigo: '0413', comunidad: 'SAN PEDRO SAN PABLO LA PRIMAVERA' },
  { codigo: '0413', comunidad: 'SAN PEDRO SAN PABLO CENTRICO' },
  { codigo: '0413', comunidad: 'SANTISIMA TRINIDAD CALLEJONES' },
  { codigo: '0413', comunidad: 'SANTISIMA TRINIDAD CENTRICO' },
  { codigo: '0413', comunidad: 'CHIMACHOY' },
  { codigo: '0413', comunidad: 'CHICAZANGA' },
  { codigo: '0413', comunidad: 'XEPARQUIY' },
  { codigo: '0413', comunidad: 'PANIMAQUIN' },
  { codigo: '0413', comunidad: 'SAN RAFAEL' },
  { codigo: '0413', comunidad: 'CAJAHUALTEN (Cajagualten)' },
  { codigo: '0413', comunidad: 'HIERBA BUENA (Yerbabuena)' },
  { codigo: '0413', comunidad: 'LOS CORRALES' },
  { codigo: '0413', comunidad: 'LOS ENCINOS' },
  { codigo: '0413', comunidad: 'CALDERAS' },
  { codigo: '0412', comunidad: 'SAN PEDRO YEPOCAPA (Yepocapa)' },
  { codigo: '0412', comunidad: 'BUENA VISTA I' },
  { codigo: '0412', comunidad: 'LA CRUZ' },
  { codigo: '0412', comunidad: 'MONTE DE LOS OLIVOS' },
  { codigo: '0412', comunidad: 'MONTE LLANO (C/S)' },
  { codigo: '0412', comunidad: 'SAN FRANCISCO LA CUCHILLA' },
  { codigo: '0412', comunidad: 'LA ESTRELLITA (C/S)' },
  { codigo: '0412', comunidad: 'CHICALVARIO' },
  { codigo: '0412', comunidad: 'NUEVA VICTORIA (C/S)' },
  { codigo: '0412', comunidad: 'EL XAB (C/S)' },
  { codigo: '0412', comunidad: 'CASERIO EL PARAISO' },
  { codigo: '0412', comunidad: 'BUENA VISTA' },
  { codigo: '0412', comunidad: 'OJO DE AGUA' },
  { codigo: '0412', comunidad: 'EL SENDERO' },
  { codigo: '0412', comunidad: 'HACIENDA DON CARLOS /LA MERCED' },
  { codigo: '0412', comunidad: 'VERSALLES EL TIGRE / COMUNIDAD LOS BRILLANTES' },
  { codigo: '0412', comunidad: 'SANTA TEREZA SUMATAN' },
  { codigo: '0412', comunidad: 'SANTA ROSA SUMATAN' },
  { codigo: '0412', comunidad: 'SANTA EMILIA' },
  { codigo: '0412', comunidad: 'SANTA CRISTINA' },
  { codigo: '0412', comunidad: 'SANGRE DE CRISTO' },
  { codigo: '0412', comunidad: 'SAN LUCAS MIRAMAR' },
  { codigo: '0412', comunidad: 'SAN JOSE MIRAFLORES' },
  { codigo: '0412', comunidad: 'SAN JOSE LA UNION' },
  { codigo: '0412', comunidad: 'SAN ANTONIO SUMATAN' },
  { codigo: '0412', comunidad: 'SAN ANTONIO EL ENCANTO' },
  { codigo: '0412', comunidad: 'RECREO' },
  { codigo: '0412', comunidad: 'PEÑA PLATA' },
  { codigo: '0412', comunidad: 'PANAJABAL/PARAISO EL XAB' },
  { codigo: '0412', comunidad: 'PALO VERDE' },
  { codigo: '0412', comunidad: 'NIMAYA' },
  { codigo: '0412', comunidad: 'MONTE CARMELO' },
  { codigo: '0412', comunidad: 'MONTE VERDE' },
  { codigo: '0412', comunidad: 'LAS VICTORIAS' },
  { codigo: '0412', comunidad: 'LAS MERCEDES' },
  { codigo: '0412', comunidad: 'LAS MARIAS' },
  { codigo: '0412', comunidad: 'LA TRINIDAD SUMATAN' },
  { codigo: '0412', comunidad: 'LA PASTORCITA' },
  { codigo: '0412', comunidad: 'LA GIRALDA' },
  { codigo: '0412', comunidad: 'LA ENSENADA' },
  { codigo: '0412', comunidad: 'LA CUCHILLA / LABOR LA CUCHILLA' },
  { codigo: '0412', comunidad: 'LA CONCHITA' },
  { codigo: '0412', comunidad: 'LA CEIBA' },
  { codigo: '0412', comunidad: 'LA ARGENTINA' },
  { codigo: '0412', comunidad: 'KANANGA' },
  { codigo: '0412', comunidad: 'EL RIACHUELO' },
  { codigo: '0412', comunidad: 'EL PATRON' },
  { codigo: '0412', comunidad: 'EL CORTIJO' },
  { codigo: '0412', comunidad: 'CHUSITA' },
  { codigo: '0412', comunidad: 'CHINAJA' },
  { codigo: '0412', comunidad: 'CASTAÑUELAS' },
  { codigo: '0412', comunidad: 'ARGELIA' },
  { codigo: '0412', comunidad: 'SIBAJÁ' },
  { codigo: '0412', comunidad: 'SANTA SOFIA' },
  { codigo: '0412', comunidad: 'NUEVA VICTORIA' },
  { codigo: '0412', comunidad: 'MONTE LLANO' },
  { codigo: '0412', comunidad: 'CHUACHILIL' },
  { codigo: '0412', comunidad: 'EL PORVENIR' },
  { codigo: '0412', comunidad: 'CHICALVARIO / EL PARAISO' },
  { codigo: '0412', comunidad: 'BETHANIA' },
  { codigo: '0412', comunidad: 'CAB. MPAL. SAN PEDRO YEPOCAPA' },
  { codigo: '0412', comunidad: 'YUCALES' },
  { codigo: '0412', comunidad: 'SAN FRANCISCO' },
  { codigo: '0412', comunidad: 'PANIMACHE II' },
  { codigo: '0412', comunidad: 'PANIMACHE I' },
  { codigo: '0412', comunidad: 'LA ESTRELLITA' },
  { codigo: '0412', comunidad: 'ROSARIO CHUARRAMOS' },
  { codigo: '0412', comunidad: 'LA CEIBA SUMATAN (P/S)' },
  { codigo: '0412', comunidad: 'SAN RAFAEL SUMATÁN' },
  { codigo: '0412', comunidad: 'ROSARIO CHURRAMOS' },
  { codigo: '0412', comunidad: 'MORELIA' },
  { codigo: '0412', comunidad: 'NUEVA VICTORIA' },
  { codigo: '0411', comunidad: 'ACATENANGO' },
  { codigo: '0411', comunidad: 'PALESTINA' },
  { codigo: '0411', comunidad: 'LAS DELICIAS' },
  { codigo: '0411', comunidad: 'EL RECUERDO MIRAMAR' },
  { codigo: '0411', comunidad: 'ESMERALDA' },
  { codigo: '0411', comunidad: 'LA PROVIDENCIA' },
  { codigo: '0411', comunidad: 'MONTE VERDE' },
  { codigo: '0411', comunidad: 'SAN DIEGO' },
  { codigo: '0411', comunidad: 'SAN FRANCISCO MIRAMAR' },
  { codigo: '0411', comunidad: 'SAN JOSE LA UNION' },
  { codigo: '0411', comunidad: 'SAN JOSE MIRAMAR' },
  { codigo: '0411', comunidad: 'SAN RAFAEL EL PANCUN' },
  { codigo: '0411', comunidad: 'SAN VICENTE PANCUN' },
  { codigo: '0411', comunidad: 'SANTA MARGARITA' },
  { codigo: '0411', comunidad: 'SANTA MARIA (SANTA ELISA)' },
  { codigo: '0411', comunidad: 'VALPARAISO' },
  { codigo: '0411', comunidad: 'CHALABAL' },
  { codigo: '0411', comunidad: 'SAN ANTONIO NEJAPA' },
  { codigo: '0411', comunidad: 'LOS PLANES' },
  { codigo: '0411', comunidad: 'FINCA EL CARMEN' },
  { codigo: '0411', comunidad: 'EL SOCORRO' },
  { codigo: '0411', comunidad: 'SAN FERNANDO' },
  { codigo: '0411', comunidad: 'PUEBLO NUEVO' },
  { codigo: '0411', comunidad: 'PACACAY' },
  { codigo: '0411', comunidad: 'PACOC' },
  { codigo: '0411', comunidad: 'EL MIRADOR' },
  { codigo: '0411', comunidad: 'PARAXAJ' },
  { codigo: '0411', comunidad: 'SANTA FELIZA' },
  { codigo: '0411', comunidad: 'JOCOTALES' },
  { codigo: '0411', comunidad: 'QUIZACHÉ (Quizajche)' },
  { codigo: '0411', comunidad: 'EL NOGAL' },
  { codigo: '0411', comunidad: 'TEHUYA' },
  { codigo: '0411', comunidad: 'TAJANCARON' },
  { codigo: '0411', comunidad: 'EL CAMPAMENTO' },
  { codigo: '0411', comunidad: 'LA SOLEDAD' },
  { codigo: '0411', comunidad: 'NUEVA ALIANZA' },
  { codigo: '0411', comunidad: 'EL JOCOTE' },
  { codigo: '0411', comunidad: 'EL TESORO' },
  { codigo: '0411', comunidad: 'CASERIO CALI' },
  { codigo: '0411', comunidad: 'EL SARE' },
  { codigo: '0411', comunidad: 'COLONIA IMEBA' },
  { codigo: '0411', comunidad: 'LA PAZ' },
  { codigo: '0411', comunidad: 'LADRILLERA' },
  { codigo: '0411', comunidad: 'IGSS' },
  { codigo: '0411', comunidad: 'SULA' },
  { codigo: '0411', comunidad: 'SAN CARLOS' },
  { codigo: '0411', comunidad: 'POTRERITO' },
  { codigo: '0411', comunidad: 'LIMONADA' },
  { codigo: '0411', comunidad: 'RESBALON' },
  { codigo: '0411', comunidad: 'SURIEL' },
  { codigo: '0411', comunidad: 'AROLDO' },
  { codigo: '0411', comunidad: 'LOS PAJALAES' },
  { codigo: '0411', comunidad: 'LA PAMPA' },
  { codigo: '0411', comunidad: 'NUEVA CONCEPCION' },
  { codigo: '0411', comunidad: 'TZIQUINYA' },
  { codigo: '0411', comunidad: 'PUERTA BLANCA' },
  { codigo: '0411', comunidad: 'FINCA LA PAMPA' },
  { codigo: '0411', comunidad: 'LA ESPERANZA' },
  { codigo: '0411', comunidad: 'LA UNION I' },
  { codigo: '0411', comunidad: 'LOS CHAPAZ' },
  { codigo: '0411', comunidad: 'LOS OLIVOS' },
  { codigo: '0411', comunidad: 'CAMPO ALEGRE' },
  { codigo: '0409', comunidad: 'PATZICIA' },
  { codigo: '0409', comunidad: '5TA CALLE ZONA 1' },
  { codigo: '0409', comunidad: 'SECTOR 3RA CALLE ZONA 2' },
  { codigo: '0409', comunidad: '4TA CALLE ZONA 3' },
  { codigo: '0409', comunidad: '3RA CALLE ZONA 4' },
  { codigo: '0409', comunidad: 'ZONA 5' },
  { codigo: '0409', comunidad: 'AV. LA REFORMA' },
  { codigo: '0409', comunidad: 'EL TANQUE' },
  { codigo: '0409', comunidad: 'EL SITAN' },
  { codigo: '0409', comunidad: 'SAJCAP' },
  { codigo: '0409', comunidad: 'SECTOR EL CALVARIO' },
  { codigo: '0409', comunidad: 'SECTOR EL CEMENTERIO ZONA 4' },
  { codigo: '0409', comunidad: 'SAN LORENZO' },
  { codigo: '0409', comunidad: 'PAHUIT' },
  { codigo: '0409', comunidad: 'SANTA MARIA CERRO ALTO' },
  { codigo: '0409', comunidad: 'CERRO ALTO' },
  { codigo: '0409', comunidad: 'PAHUUIT BAJO' },
  { codigo: '0409', comunidad: 'CAMÁN 1' },
  { codigo: '0409', comunidad: 'CAMÁN 2' },
  { codigo: '0409', comunidad: 'EL CAMÀN' },
  { codigo: '0409', comunidad: 'CAMÁN 3' },
  { codigo: '0409', comunidad: 'CAMÀN 4' },
  { codigo: '0409', comunidad: 'LA ESPERANZA' },
  { codigo: '0408', comunidad: 'SAN MIGUEL POCHUTA (Pochuta)' },
  { codigo: '0408', comunidad: 'ESQUIPULAS' },
  { codigo: '0408', comunidad: 'VILLA DE POCHUTA (Villas de Pochuta)' },
  { codigo: '0408', comunidad: 'SAN JUAN' },
  { codigo: '0408', comunidad: 'BARRIO POBRE' },
  { codigo: '0408', comunidad: 'PANCUN' },
  { codigo: '0408', comunidad: 'CEYLAN' },
  { codigo: '0408', comunidad: 'SAN MIGUELITO' },
  { codigo: '0408', comunidad: 'SAN EDUARDO' },
  { codigo: '0408', comunidad: 'EL NOJ' },
  { codigo: '0408', comunidad: 'SAN RAFAEL I' },
  { codigo: '0408', comunidad: 'SAN RAFAEL II' },
  { codigo: '0408', comunidad: 'SANTA ANA' },
  { codigo: '0408', comunidad: 'VILLA GUADALUPE' },
  { codigo: '0408', comunidad: 'VILLA RINA' },
  { codigo: '0408', comunidad: 'NUEVO AMANECER' },
  { codigo: '0408', comunidad: 'CALIFORNIA' },
  { codigo: '0408', comunidad: 'COSTA RICA' },
  { codigo: '0408', comunidad: 'EL PACAYAL' },
  { codigo: '0408', comunidad: 'EL PEÑON' },
  { codigo: '0408', comunidad: 'EL RECUERDO' },
  { codigo: '0408', comunidad: 'EL RETIRO' },
  { codigo: '0408', comunidad: 'EL ROSARIO' },
  { codigo: '0408', comunidad: 'EL SALTO' },
  { codigo: '0408', comunidad: 'FLORENCIA' },
  { codigo: '0408', comunidad: 'LA ESPERANZA' },
  { codigo: '0408', comunidad: 'LA FELICIDAD' },
  { codigo: '0408', comunidad: 'LA TORRE' },
  { codigo: '0408', comunidad: 'LA UNION' },
  { codigo: '0408', comunidad: 'MIRANDILLA' },
  { codigo: '0408', comunidad: 'CONCEPCION' },
  { codigo: '0408', comunidad: 'PACAYALITO' },
  { codigo: '0408', comunidad: 'POTOSI' },
  { codigo: '0408', comunidad: 'SAN BERNARDINO' },
  { codigo: '0408', comunidad: 'SAN CARLOS MIRAMAR' },
  { codigo: '0408', comunidad: 'SAN FRANCISCO' },
  { codigo: '0408', comunidad: 'SAN JORGE' },
  { codigo: '0408', comunidad: 'SANTA ANITA' },
  { codigo: '0408', comunidad: 'SANTA ELISA' },
  { codigo: '0408', comunidad: 'SANTA RITA' },
  { codigo: '0408', comunidad: 'SIGUAN NICAN' },
  { codigo: '0408', comunidad: 'UNION VICTORIA' },
  { codigo: '0408', comunidad: 'SAN  ALBERTO' },
  { codigo: '0408', comunidad: 'SAN MIGUEL POCHUTA CABECERA MUNICIPAL' },
  { codigo: '0408', comunidad: 'CANDELARIA' },
  { codigo: '0408', comunidad: 'SANTA MARIA' },
  { codigo: '0408', comunidad: 'LA BENDICION' },
  { codigo: '0415', comunidad: 'ZONA 1' },
  { codigo: '0415', comunidad: 'ZONA 2' },
  { codigo: '0415', comunidad: 'ZONA 3' },
  { codigo: '0415', comunidad: 'ZONA 4' },
  { codigo: '0415', comunidad: 'LAS LOMAS' },
  { codigo: '0415', comunidad: 'MANCHERÉN GRANDE' },
  { codigo: '0415', comunidad: 'LAS COLMENAS' },
  { codigo: '0415', comunidad: 'RINCÓN GRANDE' },
  { codigo: '0415', comunidad: 'RINCÓN CHIQUITO' },
  { codigo: '0415', comunidad: 'AGUA DULCE' },
  { codigo: '0415', comunidad: 'PUERTA ABAJO' },
  { codigo: '0415', comunidad: 'EL CUNTIC' },
  { codigo: '0415', comunidad: 'EL LLANO' },
  { codigo: '0415', comunidad: 'NUEVA ESPERANZA' },
  { codigo: '0415', comunidad: '29 DE SEPTIEMBRE' },
  { codigo: '0415', comunidad: 'PIERO MORARI' },
  { codigo: '0415', comunidad: 'JOYA GRANDE' },
  { codigo: '0415', comunidad: 'POTRERILLOS' },
  { codigo: '0415', comunidad: 'TULULCHE' },
  { codigo: '0405', comunidad: 'SANTA APOLONIA' },
  { codigo: '0405', comunidad: 'CHUAPARAL I' },
  { codigo: '0405', comunidad: 'CHUPARAL II' },
  { codigo: '0405', comunidad: 'ZONA 1' },
  { codigo: '0405', comunidad: 'ZONA 2' },
  { codigo: '0405', comunidad: 'ZONA 3' },
  { codigo: '0405', comunidad: 'ZONA 4' },
  { codigo: '0405', comunidad: 'COJULYA' },
  { codigo: '0405', comunidad: 'XECAJCAP' },
  { codigo: '0405', comunidad: 'XECAJCAP II' },
  { codigo: '0405', comunidad: 'CHIPATA' },
  { codigo: '0405', comunidad: 'OJER COC' },
  { codigo: '0405', comunidad: 'PANATZAN' },
  { codigo: '0405', comunidad: 'PARAJBEY' },
  { codigo: '0405', comunidad: 'XEPANIL' },
  { codigo: '0405', comunidad: 'LA PUERTA' },
  { codigo: '0405', comunidad: 'XEABAJ' },
  { codigo: '0405', comunidad: 'CHUACACAY' },
  { codigo: '0405', comunidad: 'PATZAJ' },
  { codigo: '0405', comunidad: 'CHUACHUN' },
  { codigo: '0405', comunidad: 'LOS PEREZ' },
  { codigo: '0405', comunidad: 'SALAMIT' },
  { codigo: '0405', comunidad: 'CHIQUEX' },
  { codigo: '0405', comunidad: 'LA VEGA' },
  { codigo: '0405', comunidad: 'CHOANTONIO' },
  { codigo: '0405', comunidad: 'XECUBAL' },
  { codigo: '0405', comunidad: 'XECOHIL' },
  { codigo: '0405', comunidad: 'CHIRAXAJ' },
  { codigo: '0405', comunidad: 'PACUTAN' },
  { codigo: '0405', comunidad: 'XESAJBIN' },
  { codigo: '0416', comunidad: 'EL TEJAR' },
  { codigo: '0416', comunidad: 'SAN MIGUEL MORAZAN' },
  { codigo: '0416', comunidad: 'COLONIA SANTO DOMINGO' },
  { codigo: '0416', comunidad: 'ALDEA SANTO DOMINGO' },
  { codigo: '0416', comunidad: '20 DE OCTUBRE' },
  { codigo: '0416', comunidad: 'CHIRIN' },
  { codigo: '0416', comunidad: 'BELLA VISTA' },
  { codigo: '0416', comunidad: 'SAN ANTONIO' },
  { codigo: '0416', comunidad: 'ELVIDIO SULECIO' },
  { codigo: '0416', comunidad: 'SAN JUAN' },
  { codigo: '0416', comunidad: 'CALLE REAL' },
  { codigo: '0416', comunidad: 'CALVARIO' },
  { codigo: '0416', comunidad: 'CASTELLANA' },
  { codigo: '0416', comunidad: 'PINADA' },
  { codigo: '0416', comunidad: 'RASTRO VIEJO' },
  { codigo: '0416', comunidad: 'BARREAL' },
  { codigo: '0416', comunidad: 'LOS PINOS' },
  { codigo: '0416', comunidad: 'PATRICIA DE ARZU' },
  { codigo: '0414', comunidad: 'PARRAMOS' },
  { codigo: '0414', comunidad: 'CANTON LA UNION ZONA 1' },
  { codigo: '0414', comunidad: 'CANTON LA PAZ ZONA 2' },
  { codigo: '0414', comunidad: 'CANTON LA LIBERTAD ZONA 3' },
  { codigo: '0414', comunidad: 'CANTON LA DEMOCRACIA ZONA 4' },
  { codigo: '0414', comunidad: 'LOS LLANOS' },
  { codigo: '0414', comunidad: 'LA HERMITA' },
  { codigo: '0414', comunidad: 'FINCA EL PARAISO' },
  { codigo: '0414', comunidad: 'VILLAS DE GUADALUPE' },
  { codigo: '0414', comunidad: 'PAMPAY' },
  { codigo: '0414', comunidad: 'SAN BERNABE' },
  { codigo: '0414', comunidad: 'ALDEA CHIRIJUYU' },
  { codigo: '0414', comunidad: 'ALDEA PARROJAS' },
  { codigo: '0414', comunidad: 'ALDEA CHITABURUY' },
  { codigo: '0414', comunidad: 'PARAXAY' },
  { codigo: '0414', comunidad: 'GRAVILEAS' },
  { codigo: '0414', comunidad: 'FINCA DORITA' },
  { codigo: '0406', comunidad: 'PAQUIP' },
  { codigo: '0406', comunidad: 'PALEY CENTRO' },
  { codigo: '0406', comunidad: 'PALIMA' },
  { codigo: '0406', comunidad: 'PACAYAL' },
  { codigo: '0406', comunidad: 'PALAMA' },
  { codigo: '0406', comunidad: 'PALEY BUENA VISTA' },
  { codigo: '0406', comunidad: 'XECOXOL' },
  { codigo: '0406', comunidad: 'BUENA VISTA NORTE (PILITA)' },
  { codigo: '0406', comunidad: 'PACHICHIAC' },
  { codigo: '0406', comunidad: 'PAMEZUL' },
  { codigo: '0406', comunidad: 'CHIJACINTO' },
  { codigo: '0406', comunidad: 'PACACAY' },
  { codigo: '0406', comunidad: 'VILLA NUEVA' },
  { codigo: '0406', comunidad: 'CHUARACANJAY' },
  { codigo: '0406', comunidad: 'CHICAPIR' },
  { codigo: '0406', comunidad: 'LOS PLANES' },
  { codigo: '0406', comunidad: 'PARAXQUIN' },
  { codigo: '0406', comunidad: 'PACAN' },
  { codigo: '0406', comunidad: 'VISTA HERMOSA' },
  { codigo: '0406', comunidad: 'XEPAC' },
  { codigo: '0406', comunidad: 'LA CUMBRE' },
  { codigo: '0406', comunidad: 'EL MIRADOR' },
  { codigo: '0406', comunidad: 'EL TESORO' },
  { codigo: '0406', comunidad: 'FLOR DE PARAXAJ' },
  { codigo: '0406', comunidad: 'CHIPOCOO' },
  { codigo: '0410', comunidad: 'CANTON EL PROGRESO' },
  { codigo: '0410', comunidad: 'CANTON INDEPENDENCIA' },
  { codigo: '0410', comunidad: 'CANTON LA LIBERTAD' },
  { codigo: '0410', comunidad: 'CANTON LA UNION' },
  { codigo: '0410', comunidad: 'SANTA CRUZ BALANYÁ' },
  { codigo: '0410', comunidad: 'EL ESFUERZO' },
  { codigo: '0410', comunidad: 'CHICHAVAC' },
  { codigo: '0410', comunidad: 'CHICALON' },
  { codigo: '0410', comunidad: 'CHIYAX' },
  { codigo: '0410', comunidad: 'CHIMAZAT' },
  { codigo: '0410', comunidad: 'CHUIXILON' }
]
